### ISSUE TITLE
ActiveStorage does not work when using a form object

### ISSUE THREAD

**Issue by santiagodoldan** [makandra/active_type#102] opened 2018-05-14 22:12 UTC
I'm using ActiveStorage (http://edgeguides.rubyonrails.org/active_storage_overview.html) in one model, let's say User model. Everything was working ok until I started using a form object to create users, now for some reason the ActiveStorage::Attachment record isn't being created, any ideas? I saw in the Readme that the attributes object gets overridden, not sure if that could be the cause of this issue, I'm debugging a bit on my side.

**Comment by kratob** [comment] 2018-05-22 08:19
Unfortunately, I haven't worked with ActiveStorage myself, so I have no idea what the issue might be. It seems likely that there is some interaction with Rails' built-in `attribute` logic.

**Comment by foobear** [comment] 2020-09-17 14:56
Even though the issue is rather old:
@santiagodoldan This might have been resolved in 1.4.2 as we fixed assignment through ActiveRecord's internal attribute writers.

**Comment by santiagodoldan** [comment] 2020-09-17 15:18
Hey, I don't remember what project I was working at that time, but will try to see if I can reproduce the issue and then try version 1.4.2, thanks for the heads up

**Comment by judithroth** [comment] 2021-05-14 08:46
Since it is unclear if the issue is resolved or if anyone still needs that, I'm closing this for now.
If someone runs into this again, the issue can be reopened.

**Closed by judithroth** 2021-05-14 08:46 UTC
Labels: bug, help wanted
