### ISSUE TITLE
Broken behavior with boolean attributes in rails 4.2

### ISSUE THREAD

**Issue by vevisystems** [makandra/active_type#34] opened 2015-03-09 11:33 UTC
After upgrade to rails 4.2, boolean attributes seem to be broken. Even if I do not check a checkbox, it is always interpreted as a "true" value. For instance, this validation always passes:

class AgreeForm < ActiveType::Object
 ....
  attribute :agree, :boolean
  validates :agree, :presence => true
end

Any clue?

**Comment by vevisystems** [comment] 2015-03-09 12:07
It only happens with mysql database and mysql2 adapter.

**Comment by vevisystems** [comment] 2015-03-09 22:22
It seems mysql2 adapter maps boolean values to 1-byte integer, so "false" gets converted to 0. Unfortunate as 0 is true in ruby. There is an obvious workaround (just checking for 0) but we would like it to be fixed... thanks in advance, this is a really great gem and we feel it specially useful for large applications,

**Comment by henning-koch** [comment] 2015-03-14 20:41
I'm afraid we cannot reproduce this issue.
I [added a test for the indended behavior](https://github.com/makandra/active_type/commit/5310d1d27ade93dfa45dd7e2b53c16da95fae83e), it passes.

Closing this issue for now. If you'd like to reopen it, please submit a PR with a failing test.

**Closed by henning-koch** 2015-03-14 20:41 UTC

**Comment by vevisystems** [comment] 2015-03-15 00:03
Have you tried your test with a Mysql database and mysql2 adapter instead of sqlite?

**Comment by mgraham** [comment] 2015-04-22 21:26
I am also having this problem.  Also using the mysql2 adapter.  

I've got the ActiveType test suite running with mysql2 and there are 24 errors.  With the following change, I cleared up 10 of them:

```
diff --git a/lib/active_type/type_caster.rb b/lib/active_type/type_caster.rb
index 4ea45a8..883f4c7 100644
--- a/lib/active_type/type_caster.rb
+++ b/lib/active_type/type_caster.rb
@@ -25,6 +25,12 @@ module ActiveType
         else
           native_type_cast_from_user(value)
         end
+      when :boolean
+        if value 
+          true
+        else
+          false
+        end
       when :timestamp, :datetime
         time = native_type_cast_from_user(value)
         if time && ActiveRecord::Base.time_zone_aware_attributes
```

I don't know if that's the right way to fix things, and it would be nice to clean up the other errors as well.

Should I make an issue about getting the test suite running under mysql2?  Or should this issue be reopened?

**Comment by mgraham** [comment] 2015-04-23 17:31
Incomplete pull request:  #35
