### ISSUE TITLE
ActiveType don't play well with refile

### ISSUE THREAD

**Issue by cerdiogenes** [makandra/active_type#50] opened 2015-09-23 00:08 UTC
Following the instructions in https://github.com/refile/refile#pure-ruby-classes I write the following class:

```ruby
class Files < ActiveType::Object
  extend Refile::Attachment

  attr_accessor :docs_id
  attr_accessor :activity_id
    
  attachment :docs
  attachment :activity
end
```

When I do:

```ruby
f = Files.new
f.docs = StringIO.new('teste')
```

I get the following error:

```
NoMethodError: undefined method `docs_id_will_change!' for #<Files >
from /home/kadu/.rvm/gems/ruby-2.2.1@fnix/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
```

If I make my class Pure, remove the ActiveType::Object inheritance, it's work. I don't have success while trying to understand why this is happening.

**Comment by mattbrictson** [comment] 2015-09-23 00:18
Have you tried declaring your attributes like this instead?

```ruby
attribute :docs_id, :integer
attribute :activity_id, :integer
```

**Comment by cerdiogenes** [comment] 2015-09-23 00:26
Tried just now and the error is the same.

**Comment by mattbrictson** [comment] 2015-09-23 00:44
The problem is that refile is assuming `ActiveType::Object` behaves exactly like an ActiveRecord object. This is a reasonable assumption, because `ActiveType::Object` does inherit from `ActiveRecord::Base`. However ActiveType does not support `ActiveRecord::Dirty` for its virtual attributes (which makes sense, since they are not backed by a database). Hence the error.

I think the fix has to happen on the refile side. Perhaps they can test `respond_to("#{name}_id_will_change!")` [here](https://github.com/refile/refile/blob/20ecdb3d760b8eed2d5f4bddf6dd8c673063bf2c/lib/refile/attachment/active_record.rb#L26) before making the call.

**Comment by henning-koch** [comment] 2015-09-23 13:17
Thanks for the analysis @mattbrictson .

Closing this since there is nothing we can do here.

**Comment by henning-koch** [comment] 2015-09-24 15:04
On second thought, we did make a change here.

ActiveType 0.4.2 defines some additional methods for virtual attributes, for better compatiblity with `ActiveModel::Dirty`:

- `virtual_attribute_was` always returns `nil`
- `virtual_attribute_changed?` returns true if the value is not `nil`
- `virtual_attribute_will_change!` is defined, but does nothing

**Closed by henning-koch** 2015-09-24 15:04 UTC
